/*
 * Account API
 * With the Account service you can manage your API keys and track their usage. It is important to note that unlike all other APIs, the Account API needs a master API key for authentication. For more details consult the [concept](./concepts/api-key-management-and-usage).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.account.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.account.model.ApiKeyUsage;
import com.ptvgroup.developer.client.account.model.BillingPeriod;
import com.ptvgroup.developer.client.account.model.TotalUsage;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * UsageResponse
 */
@JsonPropertyOrder({
  UsageResponse.JSON_PROPERTY_API_KEYS,
  UsageResponse.JSON_PROPERTY_TOTAL,
  UsageResponse.JSON_PROPERTY_BILLING_PERIODS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-06T11:23:34.887389Z[Etc/UTC]")
public class UsageResponse {
  public static final String JSON_PROPERTY_API_KEYS = "apiKeys";
  private List<ApiKeyUsage> apiKeys;

  public static final String JSON_PROPERTY_TOTAL = "total";
  private TotalUsage total;

  public static final String JSON_PROPERTY_BILLING_PERIODS = "billingPeriods";
  private List<BillingPeriod> billingPeriods;

  public UsageResponse() { 
  }

  public UsageResponse apiKeys(List<ApiKeyUsage> apiKeys) {
    this.apiKeys = apiKeys;
    return this;
  }

  public UsageResponse addApiKeysItem(ApiKeyUsage apiKeysItem) {
    if (this.apiKeys == null) {
      this.apiKeys = new ArrayList<>();
    }
    this.apiKeys.add(apiKeysItem);
    return this;
  }

   /**
   * This list contains the usage by API key. Only API keys which have been used in the requested period will be returned.
   * @return apiKeys
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ApiKeyUsage> getApiKeys() {
    return apiKeys;
  }


  @JsonProperty(JSON_PROPERTY_API_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiKeys(List<ApiKeyUsage> apiKeys) {
    this.apiKeys = apiKeys;
  }


  public UsageResponse total(TotalUsage total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TotalUsage getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(TotalUsage total) {
    this.total = total;
  }


  public UsageResponse billingPeriods(List<BillingPeriod> billingPeriods) {
    this.billingPeriods = billingPeriods;
    return this;
  }

  public UsageResponse addBillingPeriodsItem(BillingPeriod billingPeriodsItem) {
    if (this.billingPeriods == null) {
      this.billingPeriods = new ArrayList<>();
    }
    this.billingPeriods.add(billingPeriodsItem);
    return this;
  }

   /**
   * All billing periods.
   * @return billingPeriods
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_PERIODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BillingPeriod> getBillingPeriods() {
    return billingPeriods;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_PERIODS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingPeriods(List<BillingPeriod> billingPeriods) {
    this.billingPeriods = billingPeriods;
  }


  /**
   * Return true if this UsageResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageResponse usageResponse = (UsageResponse) o;
    return Objects.equals(this.apiKeys, usageResponse.apiKeys) &&
        Objects.equals(this.total, usageResponse.total) &&
        Objects.equals(this.billingPeriods, usageResponse.billingPeriods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKeys, total, billingPeriods);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageResponse {\n");
    sb.append("    apiKeys: ").append(toIndentedString(apiKeys)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    billingPeriods: ").append(toIndentedString(billingPeriods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `apiKeys` to the URL query string
    if (getApiKeys() != null) {
      for (int i = 0; i < getApiKeys().size(); i++) {
        if (getApiKeys().get(i) != null) {
          joiner.add(getApiKeys().get(i).toUrlQueryString(String.format("%sapiKeys%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(getTotal().toUrlQueryString(prefix + "total" + suffix));
    }

    // add `billingPeriods` to the URL query string
    if (getBillingPeriods() != null) {
      for (int i = 0; i < getBillingPeriods().size(); i++) {
        if (getBillingPeriods().get(i) != null) {
          joiner.add(getBillingPeriods().get(i).toUrlQueryString(String.format("%sbillingPeriods%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

