/* tslint:disable */
/* eslint-disable */
/**
 * Account
 * With the Account service you can manage your API keys and track their usage. It is important to note that unlike all other APIs, the Account API needs a master API key for authentication. For more details consult the [concept](./concepts/api-key-management-and-usage).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyResponse
 */
export interface ApiKeyResponse {
    /**
     * The API key.
     * @type {string}
     * @memberof ApiKeyResponse
     */
    apiKey: string;
    /**
     * The description of the API key.
     * @type {string}
     * @memberof ApiKeyResponse
     */
    description: string;
    /**
     * The date when the API key was created formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).
     * The date denotes the day from 00:00:00+00:00 until 23:59:59+00:00 based on Coordinated Universal Time (UTC).
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    created: Date;
}

/**
 * Check if a given object implements the ApiKeyResponse interface.
 */
export function instanceOfApiKeyResponse(value: object): value is ApiKeyResponse {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function ApiKeyResponseFromJSON(json: any): ApiKeyResponse {
    return ApiKeyResponseFromJSONTyped(json, false);
}

export function ApiKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'],
        'description': json['description'],
        'created': (new Date(json['created'])),
    };
}

export function ApiKeyResponseToJSON(json: any): ApiKeyResponse {
    return ApiKeyResponseToJSONTyped(json, false);
}

export function ApiKeyResponseToJSONTyped(value?: ApiKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKey': value['apiKey'],
        'description': value['description'],
        'created': ((value['created']).toISOString().substring(0,10)),
    };
}

