/* tslint:disable */
/* eslint-disable */
/**
 * Account
 * With the Account service you can manage your API keys and track their usage. It is important to note that unlike all other APIs, the Account API needs a master API key for authentication. For more details consult the [concept](./concepts/api-key-management-and-usage).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TotalServiceUsage
 */
export interface TotalServiceUsage {
    /**
     * The name of the service.
     * @type {string}
     * @memberof TotalServiceUsage
     */
    name?: string;
    /**
     * Transactions charged by this service.
     * @type {number}
     * @memberof TotalServiceUsage
     */
    transactions?: number;
    /**
     * Requests sent to this service.
     * @type {number}
     * @memberof TotalServiceUsage
     */
    requests?: number;
}

/**
 * Check if a given object implements the TotalServiceUsage interface.
 */
export function instanceOfTotalServiceUsage(value: object): value is TotalServiceUsage {
    return true;
}

export function TotalServiceUsageFromJSON(json: any): TotalServiceUsage {
    return TotalServiceUsageFromJSONTyped(json, false);
}

export function TotalServiceUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TotalServiceUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'transactions': json['transactions'] == null ? undefined : json['transactions'],
        'requests': json['requests'] == null ? undefined : json['requests'],
    };
}

export function TotalServiceUsageToJSON(json: any): TotalServiceUsage {
    return TotalServiceUsageToJSONTyped(json, false);
}

export function TotalServiceUsageToJSONTyped(value?: TotalServiceUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'transactions': value['transactions'],
        'requests': value['requests'],
    };
}

