/*
 * Account API
 *
 * With the Account service you can manage your API keys and track their usage. It is important to note that unlike all other APIs, the Account API needs a master API key for authentication. For more details consult the [concept](./concepts/api-key-management-and-usage).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.account.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.account.Model
{
    /// <summary>
    /// ApiKeysResponse
    /// </summary>
    [DataContract(Name = "ApiKeysResponse")]
    public partial class ApiKeysResponse : IEquatable<ApiKeysResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeysResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiKeysResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeysResponse" /> class.
        /// </summary>
        /// <param name="apiKeys">The list of API keys of the current subscription sorted by the date they were created in descending order so that the newest API key comes first. (required).</param>
        public ApiKeysResponse(List<ApiKeyResponse> apiKeys = default(List<ApiKeyResponse>))
        {
            // to ensure "apiKeys" is required (not null)
            if (apiKeys == null)
            {
                throw new ArgumentNullException("apiKeys is a required property for ApiKeysResponse and cannot be null");
            }
            this.ApiKeys = apiKeys;
        }

        /// <summary>
        /// The list of API keys of the current subscription sorted by the date they were created in descending order so that the newest API key comes first.
        /// </summary>
        /// <value>The list of API keys of the current subscription sorted by the date they were created in descending order so that the newest API key comes first.</value>
        [DataMember(Name = "apiKeys", IsRequired = true, EmitDefaultValue = true)]
        public List<ApiKeyResponse> ApiKeys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiKeysResponse {\n");
            sb.Append("  ApiKeys: ").Append(ApiKeys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiKeysResponse);
        }

        /// <summary>
        /// Returns true if ApiKeysResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiKeysResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiKeysResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ApiKeys == input.ApiKeys ||
                    this.ApiKeys != null &&
                    input.ApiKeys != null &&
                    this.ApiKeys.SequenceEqual(input.ApiKeys)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApiKeys != null)
                {
                    hashCode = (hashCode * 59) + this.ApiKeys.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
