/*
 * Account
 *
 * With the Account service you can manage your API keys and track their usage. It is important to note that unlike all other APIs, the Account API needs a master API key for authentication. For more details consult the [concept](./concepts/api-key-management-and-usage).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.account.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.account.Model
{
    /// <summary>
    /// BillingPeriod
    /// </summary>
    [DataContract(Name = "BillingPeriod")]
    public partial class BillingPeriod : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingPeriod" /> class.
        /// </summary>
        /// <param name="startDate">The start date of the billing period formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339)..</param>
        /// <param name="endDate">The end date of the billing period formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339)..</param>
        public BillingPeriod(DateOnly? startDate = default(DateOnly?), DateOnly? endDate = default(DateOnly?))
        {
            this.StartDate = startDate;
            this.EndDate = endDate;
        }

        /// <summary>
        /// The start date of the billing period formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).
        /// </summary>
        /// <value>The start date of the billing period formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).</value>
        /*
        <example>Thu Mar 21 00:00:00 UTC 2024</example>
        */
        [DataMember(Name = "startDate", EmitDefaultValue = true)]
        public DateOnly? StartDate { get; set; }

        /// <summary>
        /// The end date of the billing period formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).
        /// </summary>
        /// <value>The end date of the billing period formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).</value>
        /*
        <example>Sat Apr 20 00:00:00 UTC 2024</example>
        */
        [DataMember(Name = "endDate", EmitDefaultValue = true)]
        public DateOnly? EndDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingPeriod {\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
