/*
 * Account
 *
 * With the Account service you can manage your API keys and track their usage. It is important to note that unlike all other APIs, the Account API needs a master API key for authentication. For more details consult the [concept](./concepts/api-key-management-and-usage).
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.account.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.account.Model
{
    /// <summary>
    /// UsageByDay
    /// </summary>
    [DataContract(Name = "UsageByDay")]
    public partial class UsageByDay : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageByDay" /> class.
        /// </summary>
        /// <param name="date">The date formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339)..</param>
        /// <param name="transactions">Transactions charged on this day..</param>
        /// <param name="requests">Requests sent on this day..</param>
        public UsageByDay(DateOnly? date = default(DateOnly?), double? transactions = default(double?), int? requests = default(int?))
        {
            this.Date = date;
            this.Transactions = transactions;
            this.Requests = requests;
        }

        /// <summary>
        /// The date formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).
        /// </summary>
        /// <value>The date formatted according to [RFC 3339](https://tools.ietf.org/html/rfc3339).</value>
        [DataMember(Name = "date", EmitDefaultValue = true)]
        public DateOnly? Date { get; set; }

        /// <summary>
        /// Transactions charged on this day.
        /// </summary>
        /// <value>Transactions charged on this day.</value>
        [DataMember(Name = "transactions", EmitDefaultValue = true)]
        public double? Transactions { get; set; }

        /// <summary>
        /// Requests sent on this day.
        /// </summary>
        /// <value>Requests sent on this day.</value>
        [DataMember(Name = "requests", EmitDefaultValue = true)]
        public int? Requests { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsageByDay {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Transactions: ").Append(Transactions).Append("\n");
            sb.Append("  Requests: ").Append(Requests).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
